* DONE Add string search command
  CLOSED: [2015-01-03 Sat 16:19]
** Description
Search for string
** Notes
Sections: .data, .rdata, .rsrc. No unicode support.
Each string is separated by null byte. Can use fgets() and strstr().
** DONE Create find_string_addr() function in [[file:e:/Backups/D/Programming/slimdasm/utils.c::129][utils.c]]
   CLOSED: [2015-01-03 Sat 16:18]
** DONE Create print_dump_str() function for output
   CLOSED: [2015-01-03 Sat 16:19]

* TODO Add edit command
** Description
Edit binary
** Notes
Ask for starting address.
User inputs a series of bytes (with or without space separators).
Parse input string as bytes, ignoring spaces, keeping track of length.
Replace those bytes and save to new file (for testing).
** DONE Edit [[file:output.c::11][print_help()]]
   CLOSED: [2015-01-14 Wed 17:06]
** TODO Write [[file:slimdasm.c::173][case]]
** DONE Create function to duplicate file before (precursor to save edited file)
   CLOSED: [2015-01-14 Wed 21:58]

* TODO Add command to search for references to address
